"use client";

import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "motion/react";
import { toast } from "sonner";
import { z } from "zod";
import { authClient } from "@/lib/auth/auth-client";
import { Button } from "@/components/ui/botton";
import { Input } from "@/components/ui/input";

const emailSchema = z.string().email("Enter a valid email address.");

export function AuthForm({ mode }: { mode: "signin" | "signup" | "forgot" }) {
    const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
    const isSignup = mode === "signup"; const isForgot = mode === "forgot";
    async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!emailSchema.safeParse(email).success) { setError("Enter a valid email address."); return; } if (!isForgot && password.length < 8) { setError("Password must be at least 8 characters."); return; } if (isSignup && name.trim().length < 2) { setError("Enter your name."); return; } setLoading(true); try { if (isForgot) await authClient.forgetPassword({ email, redirectTo: "/auth/reset-password" }); else if (isSignup) await authClient.signUp.email({ name, email, password }); else await authClient.signIn.email({ email, password }); toast.success(isForgot ? "Reset instructions sent" : isSignup ? "Account created" : "Welcome back"); if (isForgot) router.push("/auth/sign-in"); else { const session = await authClient.getSession(); router.push(session?.user?.role === "ADMIN" ? "/admin" : "/account"); } } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Something went wrong. Please try again."); } finally { setLoading(false); } }
    async function google() { setError(""); setLoading(true); try { await authClient.signIn.social({ provider: "google", callbackURL: "/account" }); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Google sign-in failed."); setLoading(false); } }
    return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="w-full max-w-md rounded-lg border border-border bg-surface p-6 shadow-sm md:p-8"><div className="mb-8"><div className="mb-4 grid h-11 w-11 place-items-center rounded-md bg-brand text-sm font-bold text-white">C</div><h1 className="text-2xl font-bold tracking-tight text-default">{isForgot ? "Reset your password" : isSignup ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm leading-6 text-muted">{isForgot ? "Weâ€™ll send a secure reset link to your email." : "Save quotes, track requests, and manage your Cimalc Tech experience."}</p></div>{!isForgot && <Button type="button" variant="secondary" className="w-full" onClick={google} disabled={loading}>Continue with Google</Button>}{!isForgot && <div className="my-5 flex items-center gap-3 text-xs text-muted"><span className="h-px flex-1 bg-border" />or continue with email<span className="h-px flex-1 bg-border" /></div>}<form onSubmit={submit} className="space-y-4">{isSignup && <Input label="Full name" value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" />}{<Input label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" />}{!isForgot && <Input label="Password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={isSignup ? "new-password" : "current-password"} hint={isSignup ? "Use at least 8 characters." : undefined} />}{error && <p role="alert" className="rounded-sm bg-error-bg px-3 py-2 text-sm text-error">{error}</p>}<Button type="submit" className="w-full" isLoading={loading}>{isForgot ? "Send reset link" : isSignup ? "Create account" : "Sign in"}</Button></form><div className="mt-6 text-center text-sm text-muted">{isForgot ? <Link href="/auth/sign-in" className="font-medium text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Back to sign in</Link> : isSignup ? <>Already have an account? <Link href="/auth/sign-in" className="font-medium text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Sign in</Link></> : <>New to Cimalc Tech? <Link href="/auth/sign-up" className="font-medium text-brand focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand">Create an account</Link><br /><Link href="/auth/forgot-password" className="mt-3 inline-block text-xs text-muted hover:text-brand">Forgot password?</Link></>}</div></motion.div>;
}

